config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root 'static_pages#home'
  mount Sidekiq::Web => "/sidekiq"

  resources :users
  resources :channels, only: [:index, :show, :create, :edit, :update]
  resources :feeds do
    member do
      put "like" => "feeds#vote"
    end
  end
  resources :subscribes
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/channels/search', to: 'channels#search', via: 'post'
  match 'channels/new', to: 'channels#create', via: 'post'
  # match '/subscribe', to: 'subscribes#destroy', via: 'delete'
  # match '/post', to: 'posts#delete', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :type;
  belongs_to :category
  belongs_to :user
  has_many :subscribes, :dependent => :destroy
  has_many :users, through: :subscribes, source: :user
  has_many :feeds, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: true}
  validates :url, presence: true, uniqueness: {case_sensitive: true}
  validate :isRssLinkValid?

  def has_sub(user)
    user.channels.include? self
  end

  def getSubCount
    return self.subscribes.size
  end

  def checkRssLink?
    begin
      @feeds = Feedjira::Feed.fetch_and_parse url
      if @feeds.entries.size > 0
        return true
      else
        return false
      end
    rescue => e
      return false
    end
  end

  private

  def isRssLinkValid?
    errors.add(:url, "is not valid.") unless checkRssLink?
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  include SignedInUser
  skip_before_action :verify_authenticity_token

  def index
    @channels = Channel.all
    @newChannel = Channel.new
    @categories = Category.all
  end

  def show
    @channel = Channel.find(params[:id])
    s = "select * from feeds where channel_id = " + @channel.id.to_s
    @feeds = Feed.where(channel_id: @channel.id).paginate(page: params[:page], per_page: 10).order('created_at Desc')
    @fromRss = false
    if (@feeds == nil or @feeds.entries.size == 0)
      @feeds = Feedjira::Feed.fetch_and_parse @channel.url
      @fromRss = true
    end
  end

  def edit
    @channel = Channel.find(params[:id])
    @categories = Category.all
  end

  def search
    s = "select * from channels where LOWER(name) LIKE LOWER('%" + params[:channel][:name] +
        "%') and LOWER(url) LIKE LOWER('%" + params[:channel][:uri] + "%')"
    @channels = Channel.find_by_sql(s)
    respond_to do |format|
      format.html
      format.js {render :action => "update_channels"}
    end
  end

  def update
    @channel = Channel.find(params[:id])

    if @channel.update(channel_params)
      ChannelUpdateWorker.perform_async @channel.id
      redirect_to @channel
    else
      @categories = Category.all
      render 'edit'
    end
  end

  def create
    @channel = Channel.new(channel_params)
    if addChannel?
      respond_to do |format|
        if @channel.save
          @channels = Channel.all
          RssWorker.perform_async
          format.html
          format.js {render :action => "afterChannelCreation"}
        else
          format.html
          format.js {render :action => "cantAddChannel"}
        end
      end
    else
      if checkRssLinkAction?
        @rssCheck = @channel.checkRssLink?
        respond_to do |format|
          format.js {render :action => "rssCheck"}
        end
      end
    end
  end


  private

  def channel_params
    params.require(:channel).permit(:name, :url, :description, :category_id, :type_id, :user_id, :site_page)
  end

  def checkRssLinkAction?
    params[:commit] == "Проверить ссылку"
  end

  def addChannel?
    params[:commit] == "Добавить"
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper

end

app/views/channels/_addChannelForm.html.erb
<div class="fixed right-side-form">
  <h3>Не нашли нужный канал?</h3>
  <h3>Добавьте его!</h3>

  <div class="form-group col-lg-12">
    <%= form_for(@newChannel, remote: true) do |f| %>
      <%= f.text_field :name, placeholder: "Название", class: "form-control mt-3" %>
      <%= f.text_area :description, placeholder: "Описание", class: "form-control mt-3" %>
      <%= f.text_field :url, placeholder: "RSS ссылка", class: "form-control mt-3" %>
      <%= f.text_field :site_page, placeholder: "Ссылка на сайт", class: "form-control mt-3" %>
      <%= f.hidden_field :type_id, value: "1" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.select(:category_id, options_for_select(@categories.map {|c| [c.name, c.id]}), {}, {class: "form-control mt-3 h-100"}) %>
      <div class="form-inline">
        <%= f.submit "Добавить", class: "btn btn-primary mt-3" %>
        <%= f.submit "Проверить ссылку", class: "btn btn-primary mt-3 ml-4" %>
      </div>

      <span id="channelValidation"/>
      <div class="clear"></div>
    <% end %>
  </div>

</div>

app/views/channels/_channel.html.erb
<div class="col-lg-4 col-md-6 col-sm-6 col-xs-12" data-aos="fade-right">
  <div class="col-lg-12 col-xs-12">
    <div id="<%= channel.id %>" class="blog-column">
      <div class="hidden">
        <%= @channel = channel %>
      </div>
      <%= link_to channel.name, channel, class: "channel_name" %>
      <h4><%= channel.category.name %></h4>
      <p class="channel_description"><%= channel.description %></p>
      <%= render "channels/subscribe_form" %>
    </div>
  </div>
</div>

app/views/channels/_channelAdded.html.erb
<span id="channelValidation" class="good">
Канал добавлен
</span>

app/views/channels/_channels.html.erb
<% i = 0 %>
<div id="channel_list">
  <% while i < @channels.entries.size %>
    <div class="row">
      <%= render "channels/channel", :channel => @channels.entries[i] %>
      <% i += 1 %>
      <% if (i < @channels.entries.size) %>
        <%= render "channels/channel", :channel => @channels.entries[i] %>
      <% end %>
      <% i += 1 %>
      <% if (i < @channels.entries.size) %>
        <%= render "channels/channel", :channel => @channels.entries[i] %>
      <% end %>
    </div>
    <div style="margin:40px 0px;"></div>
    <% i += 1 %>
  <% end %>
</div>

app/views/channels/_dialog.html.erb
<div class="modal fade"
     id="dialog" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel"
     aria-hidden="true"
     data-backdrop="static"
     data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close"
                data-dismiss="modal"
                aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/channels/_editChannelForm.html.erb
<div class="form-group col-lg-12">
  <%= form_with(model: @channel, local: true) do |f| %>
    <%= f.text_field :name, placeholder: "Название", class: "form-control mt-3" %>
    <%= f.text_area :description, placeholder: "Описание", class: "form-control mt-3" %>
    <%= f.text_field :url, placeholder: "RSS ссылка", class: "form-control mt-3" %>
    <%= f.text_field :site_page, placeholder: "Ссылка на сайт", class: "form-control mt-3" %>
    <%= f.hidden_field :type_id, value: "1" %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.select(:category_id, options_for_select(@categories.map {|c| [c.name, c.id]}), {}, {class: "form-control mt-3 h-100"}) %>
    <div class="form-inline">
      <%= f.submit "Сохранить", class: "btn btn-primary mt-3" %>
    </div>

    <span id="channelValidation"/>
    <div class="clear"></div>
  <% end %>
  <% if @channel.errors.any? %>
    <div id="error_explanation">
      <h4>
        Упс. Не удалось обновить канал
      </h4>
      <ul>
        <% @channel.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= link_to 'Back', @channel %>
</div>

app/views/channels/_goodRss.html.erb
<span id="channelValidation" class="good">
Успешно! Указана рабочая ссылка
</span>

app/views/channels/_search_form.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="input-group">
      <form>
        <input type="text" id="channelNameSearch" class="form-control", placeholder="Название канала"/>
        <br/>
        <br/>
        <input type="text" id="channelUriSearch" class="form-control", placeholder="RSS ссылка"/>
      </form>
    </div>
  </div>
</div>

app/views/channels/_subscribe.html.erb
<%= form_for(user.subscribes.build(channel_id: @channel.id),
             html: {method: :post},
             remote: true) do |f| %>
  <div><%= f.hidden_field :channel_id %></div>
  <div><%= f.hidden_field :user_id %></div>
  <%= f.submit "Подписка", class: "subscribe-button button pull-right col-lg-8"%>
<% end %>

app/views/channels/_subscribe_form.html.erb
<div class="col-lg-12 pull-right" id="sub-form<%= @channel.id %>">
  <% if current_user.subscribing?(@channel) %>
    <%= render 'channels/unsubscribe', :user => current_user %>
  <% else %>
    <%= render 'channels/subscribe', :user => current_user %>
  <% end %>
  <ul class="col-lg-3 blog-detail list-inline pull-right" style="margin-right: 10px; padding: 0;">
    <li><i class="fa fa-user"></i><%= @channel.getSubCount %></li>
  </ul>
</div>

app/views/channels/cantAddChannel.js.erb
$('#channelValidation').replaceWith('<%= escape_javascript(render :partial => 'channels/cantAddChannel') %>')

app/views/channels/editChannel.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Customer");

// Render the edit form
$('.modal-body').html('<%= j render("channels/editChannelForm") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
//$('#dialog').on('shown.bs.modal', function () {
//    $('.first_input').focus()
//})

app/views/channels/rssCheck.js.erb
if (<%= @rssCheck %>) {
    $('#channelValidation').replaceWith('<%= escape_javascript(render :partial => 'channels/goodRss') %>')
} else {
    $('#channelValidation').replaceWith('<%= escape_javascript(render :partial => 'channels/badRss') %>')
}

app/views/channels/show.html.erb
<% provide(:title, @channel.name) %>
<div class="content">
  <div class="blog">
    <div class="row">
      <div class="col-lg-12">
        <h2><span class="ion-minus"/><%= @channel.name %><span class="ion-minus"/></h2>
        <h4><span class="ion-minus"/><%= @channel.category.name %><span class="ion-minus"/></h4>
        <p style="margin-left: 20px;"><%= @channel.description %></p><br>
        <% if @channel.user.id == current_user.id %>
          <%= link_to edit_channel_path(@channel), class: "btn btn-primary a-btn-slide-text" do %>
            <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
            <span><strong>Обновить</strong></span>
          <% end %>
        <% end %>
        <div class="col-lg-5 pull-right">
          <%= render "channels/subscribe_form", :user => current_user %>
        </div>
      </div>
    </div>
    <hr style="border-top: 2px solid #eeeeee"/>
    <% i = 0 %>
    <% while i < @feeds.entries.size %>
      <div class="row">
        <%= render "feeds/feed_on_channel_page", :feed => @feeds.entries[i] %>
        <% i += 1 %>
        <% if (i < @feeds.entries.size) %>
          <%= render "feeds/feed_on_channel_page", :feed => @feeds.entries[i] %>
        <% end %>
      </div>
      <div style="margin:40px 0px;"></div>
      <% i += 1 %>
    <% end %>
    <% unless @fromRss %>
      <%= will_paginate @feeds %>
    <% end %>
  </div>
</div>