config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root 'static_pages#home'
  mount Sidekiq::Web => "/sidekiq"

  resources :users
  resources :channels, only: [:index, :show, :create, :edit, :update]
  resources :feeds do
    member do
      put "like" => "feeds#vote"
    end
  end
  resources :subscribes
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/channels/search', to: 'channels#search', via: 'post'
  match 'channels/new', to: 'channels#create', via: 'post'
  # match '/subscribe', to: 'subscribes#destroy', via: 'delete'
  # match '/post', to: 'posts#delete', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/feed.rb
class Feed < ApplicationRecord
  acts_as_votable
  validates :url, presence: true, uniqueness: {case_sensitive: true}

  belongs_to :channel

  self.per_page = 10
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  include SignedInUser

  def index
    @feeds = getRecentFeeds current_user.channels.entries.map(&:id)
    @topFeeds = getTopFeeds Channel.all.entries.map(&:id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def getRecentFeeds(ids)
    Feed.where(channel_id: ids).paginate(page: params[:page], per_page: 5).order('created_at Desc')
  end

  def getTopFeeds(ids)
    Feed.where(channel_id: ids).order(:cached_votes_total => :desc).limit(5)
  end

  def vote
    @feed = Feed.find(params[:id])
    if !current_user.liked? @feed
      @feed.liked_by current_user
    elsif current_user.liked? @feed
      @feed.unliked_by current_user
    end
  end
end

app/views/feeds/_feed.html.erb
<div class="row col-lg-12 col-md-12 col-sm-12 col-xs-12" data-aos="fade-right">
  <div class="blog-column">
    <span><%= feed.title %></span>
    <ul class="blog-detail list-inline">
      <li><i class="fa fa-user"></i><%= feed.channel.name %></li>
      <li><i class="fa fa-clock-o"></i><%= convertDate feed.created_at %></li>
    </ul>
    <p><%= feed.summary %></p>
    <a href="<%= getFeedUrl(feed.url, feed.channel.site_page) %>">Читать</a>
    <% @class = "like-btn" + feed.id.to_s %>
    <% @likesCount = "likes-count" + feed.id.to_s %>
    <% if current_user.liked? feed %>
      <% @class += " liked" %>
    <% end %>
    <%= link_to like_feed_path(feed), method: :put, remote: :true, class: @class do %>
      <ul class="col-lg-3 list-inline">
        <li><i class="fa fa-thumbs-up fa-1x"></i></li>
        <li class="<%= @likesCount %>"><%= feed.get_upvotes.size %></li>
      </ul>
    <% end %>
  </div>
  <hr class="col-lg-12" style="border-top: 1px solid #eeeeee"/>
</div>

app/views/feeds/_feed_on_channel_page.html.erb
<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12" data-aos="fade-right">
  <!--    <div class="col-lg-6 col-xs-12">-->
  <!--      <img class="left" alt="" width="100%" src="<%#= "#{@feed.image}" %>">-->
  <!--    </div>-->
  <div class="col-lg-12 col-xs-12">
    <div class="blog-column">
      <span><%= feed.title %></span>
      <ul class="blog-detail list-inline">
        <li><i class="fa fa-user"></i><%= @channel.name %></li>
        <% if @fromRss %>
          <li><i class="fa fa-clock-o"></i><%= convertDate feed.published %></li>
        <% else %>
          <li><i class="fa fa-clock-o"></i><%= convertDate feed.created_at %></li>
        <% end %>
      </ul>
      <p><%= feed.summary %></p>
      <a href="<%= getFeedUrl(feed.url, @channel.site_page) %>">Читать</a>
      <% unless @fromRss %>
        <% @class = "like-btn" + feed.id.to_s %>
        <% @likesCount = "likes-count" + feed.id.to_s %>
        <% if current_user.liked? feed %>
          <% @class += " liked" %>
        <% end %>
        <%= link_to like_feed_path(feed), method: :put, remote: :true, class: @class do %>
          <ul class="col-lg-3 list-inline">
            <li><i class="fa fa-thumbs-up fa-1x"></i></li>
            <li class="<%= @likesCount %>"><%= feed.get_upvotes.size %></li>
          </ul>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/feeds/index.html.erb
<div class="content">
  <div class="col-lg-6">
    <h2 class="mt-3">Последние новости:</h2>
    <div id="recentNews" class="blog col-lg-11 scrollable">
      <%= render @feeds %>
    </div>
    <div id="infinite-scrolling">
      <%= will_paginate %>
    </div>
  </div>
  <div class="col-lg-6">
    <h2 class="mt-3">Топ 5:</h2>
    <div id="topNews" class="blog col-lg-11 scrollable">
      <%= render @topFeeds %>
    </div>
  </div>

</div>

app/views/feeds/index.js.erb
$('#recentNews').append('<%= j render @feeds %>');
<% if @feeds.next_page %>
$('.pagination').replaceWith('<%= j will_paginate @feeds %>');
<% else %>
$(window).off('scroll');
$('.pagination').remove();
<% end %>

app/views/feeds/vote.js.erb
var likeBtn = ".like-btn" + <%= @feed.id %>;
var likesCount = ".likes-count" + <%= @feed.id.to_s %>
    <% if current_user.liked? @feed %>
    $(likeBtn).addClass('liked');
    <% else %>
    $(likeBtn).removeClass('liked');
    <% end %>
    $(likesCount).html("<%= @feed.get_upvotes.size %>")