config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  root 'static_pages#home'
  mount Sidekiq::Web => "/sidekiq"

  resources :users
  resources :channels, only: [:index, :show, :create, :edit, :update]
  resources :feeds do
    member do
      put "like" => "feeds#vote"
    end
  end
  resources :subscribes
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/channels/search', to: 'channels#search', via: 'post'
  match 'channels/new', to: 'channels#create', via: 'post'
  # match '/subscribe', to: 'subscribes#destroy', via: 'delete'
  # match '/post', to: 'posts#delete', via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/channel.rb
class Channel < ApplicationRecord
  belongs_to :type;
  belongs_to :category
  belongs_to :user
  has_many :subscribes, :dependent => :destroy
  has_many :users, through: :subscribes, source: :user
  has_many :feeds, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: true}
  validates :url, presence: true, uniqueness: {case_sensitive: true}
  validate :isRssLinkValid?

  def has_sub(user)
    user.channels.include? self
  end

  def getSubCount
    return self.subscribes.size
  end

  def checkRssLink?
    begin
      @feeds = Feedjira::Feed.fetch_and_parse url
      if @feeds.entries.size > 0
        return true
      else
        return false
      end
    rescue => e
      return false
    end
  end

  private

  def isRssLinkValid?
    errors.add(:url, "is not valid.") unless checkRssLink?
  end
end

app/models/feed.rb
class Feed < ApplicationRecord
  acts_as_votable
  validates :url, presence: true, uniqueness: {case_sensitive: true}

  belongs_to :channel

  self.per_page = 10
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order('created_at DESC') }
  validates :user_id, presence: true
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
  belongs_to :user
  belongs_to :channel
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, presence: true, uniqueness: {case_sensitive: false}
end

app/models/user.rb
class User < ApplicationRecord
  acts_as_voter
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save {self.email = email.downcase}
  before_create :create_remember_token
  validates :name, presence: true, length: {maximum: 50}
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  validates :password, length: {minimum: 6}
  has_secure_password

  has_many :posts, dependent: :destroy
  has_many :subscribes, :dependent => :destroy
  has_many :channels, through: :subscribes, source: :channel

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    posts
  end

  def subscribing?(channel)
    subscribes.find_by(channel_id: channel.id )
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  include SignedInUser

  def index
    @feeds = getRecentFeeds current_user.channels.entries.map(&:id)
    @topFeeds = getTopFeeds Channel.all.entries.map(&:id)
    respond_to do |format|
      format.html
      format.js
    end
  end

  def getRecentFeeds(ids)
    Feed.where(channel_id: ids).paginate(page: params[:page], per_page: 5).order('created_at Desc')
  end

  def getTopFeeds(ids)
    Feed.where(channel_id: ids).order(:cached_votes_total => :desc).limit(5)
  end

  def vote
    @feed = Feed.find(params[:id])
    if !current_user.liked? @feed
      @feed.liked_by current_user
    elsif current_user.liked? @feed
      @feed.unliked_by current_user
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    redirect_to @post
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Новостник"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end


  def show_svg(path)
    File.open("app/assets/images/#{path}", "rb") do |file|
      raw file.read
    end
  end

  def convertDate(date)
    DateFormat.change_to(date, "ONLY_DATE")
  end

  def getFeedUrl(feed_url, site_page)
    if (feed_url.include? "http")
      return feed_url
    elsif site_page != nil
      return site_page + feed_url
    else
      return "#"
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper

end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def is_current_user(user)
    @current_user == user
  end

  def current_user=(user)
    @current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def currentUserId
    return "" if current_user == nil
    return current_user.id
  end
  def current_user?(user)
    user == current_user
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</div>
</footer>

app/views/layouts/_header.html.erb
<div class="header fixed pull-left">
  <ul class="menu__list">
    <li class="menu__group">
      <%= link_to "Новости", feeds_path %>
    </li>
    <% if signed_in? %>
      <li class="menu__group">
        <%= link_to "Мой профиль", current_user %>
      </li>
      <li class="menu__group">
        <%= link_to "Пользователи", users_path %>
      </li>
      <li class="menu__group">
        <%= link_to "Каналы", channels_path, method: "get" %>
      </li>
      <li class="menu__group">
        <%= link_to "Выйти", signout_path, method: "delete" %>
      </li>
    <% else %>
      <li class="menu__group"><%= link_to "Войти", signin_path %></li>
    <% end %>
    <li class="menu__group">
      <%= link_to "Помощь", help_path %>
    </li>
  </ul>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link href='https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css' rel='stylesheet prefetch'>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>

<!-- ICONS -->
<svg id="svg-source" height="0" version="1.1" xmlns="http://www.w3.org/2000/svg"
     style="position: absolute">
  <g id="man-people-user" data-iconmelon="Streamline Icon Set:de32eb2621491c1a881a9fe846236da1">
    <g id="Expanded">
      <g>
        <g>
          <path d="M16.028,20c-4.764,0-8.639-4.486-8.639-10s3.875-10,8.639-10c4.763,0,8.638,4.486,8.638,10
				S20.791,20,16.028,20z M16.028,1.333C12,1.333,8.722,5.221,8.722,10s3.277,8.667,7.306,8.667c4.029,0,7.306-3.888,7.306-8.667
				S20.057,1.333,16.028,1.333z"></path>
        </g>
        <g>
          <path d="M31.988,32H0.012v-4.515c0-1.967,1.245-3.733,3.097-4.395l8.224-2.266v-2.77h1.333v3.785L3.51,24.361
				c-1.275,0.458-2.165,1.72-2.165,3.124v3.182h29.309v-3.182c0-1.404-0.889-2.666-2.213-3.139l-9.107-2.506v-3.758h1.332v2.742
				l8.178,2.251c1.9,0.677,3.145,2.442,3.145,4.409V32z"></path>
        </g>
        <g>
          <path d="M21.865,8.812c-0.045,0-0.09-0.001-0.137-0.003c-1.5-0.055-3.25-1.004-4.361-2.287
				C16.59,7.513,15.48,8.15,14.106,8.383c-2.403,0.413-5.152-0.51-5.988-1.321l0.928-0.957c0.403,0.391,2.69,1.329,4.836,0.964
				c1.332-0.226,2.292-0.911,2.854-2.034l0.558-1.114l0.617,1.082c0.738,1.292,2.508,2.425,3.867,2.475
				c0.604,0.016,1.033-0.165,1.307-0.571l1.105,0.745C23.686,8.403,22.863,8.812,21.865,8.812z"></path>
        </g>
      </g>
    </g>
  </g>
  <g id="lock-locker" data-iconmelon="Streamline Icon Set:5d43c6f45cdbecfd5b8a12bc9e5dd33c">
    <g id="Expanded">
      <g>
        <g>
          <circle cx="16" cy="20" r="1.333"></circle>
        </g>
        <g>
          <path d="M16,25.333c-0.369,0-0.667-0.298-0.667-0.666v-4C15.333,20.298,15.631,20,16,20s0.667,0.298,0.667,0.667
				v4C16.667,25.035,16.369,25.333,16,25.333z"></path>
        </g>
        <g>
          <path d="M28,32H4V12h24V32z M5.333,30.667h21.333V13.333H5.333V30.667z"></path>
        </g>
        <g>
          <path d="M24,12.667h-1.333V8c0-3.676-2.991-6.667-6.667-6.667c-3.676,0-6.667,2.99-6.667,6.667v4.667H8V8
				c0-4.412,3.588-8,8-8c4.411,0,8,3.588,8,8V12.667z"></path>
        </g>
      </g>
    </g>
  </g>
</svg>
<!-- ICONS -->

<div class="wrapper">
  <%= render 'layouts/header' %>
  <div class="clear"></div>
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <%= yield %>
</div>
<span id="currentUser" class="hidden"><%= currentUserId %></span>
</body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Форма содержит <%= pluralize(@user.errors.count, "Ошибки") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>